### PR TITLE
fix: wikia data parsing

### LINKED ISSUE #307: :bug: wiki lua errors
### Describe the bug

The Wikia team added more breaking content to their data modules

### NodeJS Version

15 (ci)

### npm Version

(ci)

### warframe-items Version

latest

### Access Method

github download

### What happened?

The build is breaking due to the Wikia team adding more breaking content to their data modules. We should either remove them ourselves from the modules or replace the offending lines when we clone their data. 

```log
Error: Error: Command failed: lua ./tmp/dataraw.lua > ./tmp/dataraw.json
lua: ./tmp/dataraw.lua:80: <eof> expected near 'print'
```

### LINKED ISSUE #311: :bug: Inconsistency in labelling as tradeable/untradeable
Damaged necramech parts are currently listed as untradeable, which is not true.
Also, prime weapons (and their components) are listed as tradeable, whereas prime warframes are listed as untradeable (but their components are tradeable). Is there any reason for this inconsistency? If it's on DE's end then I guess there's nothing that can be done about it, but if not then could this be cleaned up so that all primes behave the same way?

### LINKED ISSUE #313: :bug: Inconsistent kitgun types
**Is your enhancement request related to a problem? Please describe.**
The value of fortuna kitguns, type key, are `Kitgun Component` and deimos kitguns, type key, are `Pistol`.

**Describe the upgrade you'd like**
Set the type key of all kitguns to `Pistol` as it makes more sense in my head.

**Additional context**
```json
[
   {
      "name":"Catchmoon",
      "type":"Kitgun Component"
   },
   {
      "name":"Gaze",
      "type":"Kitgun Component"
   },
   {
      "name":"Rattleguts",
      "type":"Kitgun Component"
   },
   {
      "name":"Tombfinger",
      "type":"Kitgun Component"
   },
   {
      "name":"Sporelacer",
      "type":"Pistol"
   },
   {
      "name":"Vermisplicer",
      "type":"Pistol"
   }
]
```

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? 
closes #307
closes #311
closes #313 

---

### Reproduction steps
1. Support parsing multiple urls for individual categories
2. de-nest 1-deep objects
3. Map infinite values to undefined
4. Replace axios in wikia parsing with node-fetch (we already had node-fetch in use, this just makes usage consistent)
5. Update types for tradability. make damaged necramech bits tradable and built primes untradable
6. Stop using wikia for types

---

### Evidence/screenshot/link to line

there's lots

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter through `npm run lint`? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

### CODE REVIEW

**Comment by AyAyEm** [comment]
Is changing kitguns type from `Pistol` and `Kitgun Component` to `Kitgun Pistol` desired? If so let's modify the typings and also close the #313

**Comment by TobiTenno** [comment]
> Is changing kitguns type from `Pistol` and `Kitgun Component` to `Kitgun Pistol` desired? If so let's modify the typings and also close the #313

see comment on #313

**Comment by AyAyEm** [comment]
> see comment on #313
I'll review this PR once we have decided what to do with #313

**Review by AyAyEm — CHANGES_REQUESTED** [review]
There seems to be many items which the `tradable` value is set to `false` like ignis wraith. Here's a list of items which is set to false when it should be true: https://pastebin.com/raw/AntrB1V4
Just mind that i haven't checked every item in it nor i thought of a possible fix for this issue.

**Comment by AyAyEm** [comment]
I don't know if it's intended but these items don't have a `wikiaThumbnail` anymore
https://pastebin.com/raw/QdRCp6RC

**Comment by AyAyEm** [comment]
> 1. built primes are not tradable, which is why I explicitly made a change to make those untradable (see [Inconsistency in labelling as tradeable/untradeable #311](https://github.com/WFCD/warframe-items/issues/311))
> 2. any that don't have thumbnails probably don't have good matches. I mentioned multiple places that there will probably be more to do down the line.
> 3. I'll take a look at the mods missing images. This wouldn't have removed any, as all of them were removed by the change to stop parsing a good bit of wiki data on master.

Based on your points i've refined the list https://pastebin.com/raw/4RvEdpmU

**Comment by TobiTenno** [comment]
The braton and lato vandal aren't tradable

**Comment by TobiTenno** [comment]
primed mods in that list are getting set like that because of their type that was coming from wikia is now switched to using our mappings, which i'm updating. looks like `/Mod/Rifle` was set but not `/Mods/Rifle`, so that's getting added. I'm tweaking how i do the built item checking for primes

File: build/tradable.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
+const builtUntradable = ['Warframe', 'Throwing', 'Shotgun', 'Rifle', 'Pistol', 'Melee', 'Sword And Shield']
+const tradableConditions = (i) => !(builtUntradable.includes(i.type) && i.name.match(/Prime/ig))
```
Comment (AyAyEm) [inline build/tradable.js:2]: Could you rename i to item? as it's commonly associated to index.
```suggestion
const tradableConditions = (item) => !(builtUntradable.includes(item.type) && item.name.match(/Prime/ig))
```

File: config/overrides.json [hunk 2]
```diff
@@ -147,5 +147,8 @@
   },
   "/Lotus/Types/Recipes/Kubrow/Collars/PrimeKubrowCollarABuckleComponent": {
     "ducats": 65
+  },
+  "/Lotus/Weapons/Tenno/Pistol/LatoVandal": {
+    "tradable": false
   }
```
Comment (AyAyEm) [inline config/overrides.json:153]: Could you also add an override for braton vandal?
```suggestion
  },
  "/Lotus/Weapons/Tenno/Rifle/VIPRifle": {
    "tradable": false
  }
```

File: build/tradable.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+  'Glyph', 'Sigil', 'Fur Color', 'Syandana', 'Fur Pattern', 'Color Palette', 'Node', 'Exalted Weapon']
+const tradableRegex = /(Prime|Vandal|Wraith\w|\wWraith|Rakta|Synoid|Sancti|Vaykor|Telos|Secura|Ayatan|Prisma|DamagedMech)(?!Derelict)/i
+const untradableRegex = /(Glyph|Mandachord|Greater.*Lens|Sugatra|\[|SentinelWeapons|Toroid|Bait|([A-Za-z]+ (Relic)))|Umbral|Sacrificial/i
+
+/**
+ * Check if an item is tradable
+ * @param {module:warframe-items.Item} item
+ * @returns {boolean}
+ */
+module.exports = (item) => {
```
Comment (AyAyEm) [inline build/tradable.js:17]: What do you think about naming this function instead of just using an arrow function? Sometimes it helps debugging.
```suggestion
module.exports = function isTradable(item) {
```

File: build/tradable.js [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+  const notFiltered = !untradableTypes.includes(item.type) &&
+    !item.name.match(untradableRegex) &&
+    !item.uniqueName.match(untradableRegex) &&
+    (item.productCategory ? !item.productCategory.match(/(SpecialItems)/) : true)
+  const tradableByType = !!(tradableTypes.includes(item.type) && notFiltered)
+  const tradableByName = !!((item.uniqueName.match(tradableRegex) || item.name.match(tradableRegex)) && notFiltered)
+  const tradableByProp = !!((item.isAugment) && notFiltered)
```
Comment (AyAyEm) [inline build/tradable.js:24]: Is having `!!` with additional `()` enclosing the booleans meant for readability? I personally don't like it much, because it's rare to see it.

File: build/wikia/transformers/transformMod.js [hunk 5]
```diff
@@ -17,10 +17,10 @@ module.exports = async (oldMod, imageUrls) => {
     newMod = {
       name: Name,
       url: `https://warframe.fandom.com/wiki/${encodeURIComponent(Name.replace(/\s/g, '_'))}`,
-      thumbnail: imageUrls[Image],
       transmutable: Transmutable,
       introduced: Introduced
     }
+    newMod.thumbnail = imageUrls[Image]
```
Comment (AyAyEm) [inline build/wikia/transformers/transformMod.js:23]: Why not set the thumbnail inside the newMod object? imageUrls can be null or undefined so it'll throw an error? If so could you make a check instead? Same thing happens in transformWarframe and transformWeapon.

**Review by AyAyEm — CHANGES_REQUESTED** [review]

File: build/wikia/transformers/transformMod.js (hunk 5 above)
Comment (AyAyEm) [reply build/wikia/transformers/transformMod.js:23]: Also if you pretend to change it anyway in a later pr you can just check this as resolved.

**Comment by AyAyEm** [comment]
> 3. I'll take a look at the mods missing images. This wouldn't have removed any, as all of them were removed by the change to stop parsing a good bit of wiki data on master.

Also i don't see not having wikiaThumbnail in certain items as a breaking change so i don't think there'll be a problem to just fix it later. But it's not true that this pr did not remove it, as you can see here: https://pastebin.com/raw/hiiARwNp (oldItem refers to master branch items)

File: build/parser.js [hunk 6]
```diff
@@ -107,6 +107,7 @@ class Parser {
 
     if (result.rewardName) result.uniqueName = result.rewardName
     this.addType(result)
+    // this.addDamage(result)
```
[the remark this answers is not in the document]
Comment (TobiTenno) [reply build/parser.js:110]: Yes, see later issue. I got it wishing but didn't mean to fully include it, so I removed the addition to the actual data for now

File: build/parser.js [hunk 7]
```diff
@@ -502,21 +530,7 @@ class Parser {
...
-    const untradableRegex = /(Glyph|Mandachord|Greater.*Lens|Sugatra|\[|SentinelWeapons|Toroid|Bait|([A-Za-z]+ (Relic)))|Umbral|Sacrificial/i
-    const notFiltered = !untradableTypes.includes(item.type) &&
-      !item.name.match(untradableRegex) &&
-      !item.uniqueName.match(untradableRegex) &&
-      (item.productCategory ? !item.productCategory.match(/(SpecialItems)/) : true)
-    const tradableByType = !!(tradableTypes.includes(item.type) && notFiltered)
-    const tradableByName = !!((item.uniqueName.match(tradableRegex) || item.name.match(tradableRegex)) && notFiltered)
-    const tradableByProp = !!((item.isAugment) && notFiltered)
-    item.tradable = tradableByType || tradableByName || tradableByProp
+    item.tradable = require('./tradable')(item)
```
[the remark this answers is not in the document]
Comment (TobiTenno) [reply build/parser.js:533]: We do this elsewhere, but yes, I can

File: build/tradable.js (hunk 3 above)
Comment (TobiTenno) [reply build/tradable.js:17]: It's literally in it's own file...

File: build/wikia/transformers/transformMod.js (hunk 5 above)
Comment (TobiTenno) [reply build/wikia/transformers/transformMod.js:23]: I don't really like them implication of saying I'll pretend to change something. It's disingenuous.

File: build/tradable.js (hunk 3 above)
Comment (AyAyEm) [reply build/tradable.js:17]: Yeah i guess it doesn't matter much in this case

File: build/wikia/transformers/transformMod.js (hunk 5 above)
Comment (AyAyEm) [reply build/wikia/transformers/transformMod.js:23]: Sorry for my english, in portuguese pretender means to intend, so i was asking if you will change it in the a future pr like you mentioned in 314

File: build/parser.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (AyAyEm) [reply build/parser.js:533]: Didn't saw it, your choice then.

File: build/tradable.js (hunk 4 above)
Comment (TobiTenno) [reply build/tradable.js:24]: it's for massaging values to booleans, since `notFiltered` can be an object, and could ultimately trickle into being the value on `tradable`, which i also want to for sure be a boolean.

File: build/wikia/transformers/transformMod.js (hunk 5 above)
Comment (TobiTenno) [reply build/wikia/transformers/transformMod.js:23]: Ah, I get what you meant now. My apologies for misunderstanding your intent. I had no plans on altering what it does right now. Given that this is a generated field and could potentially fail unreliably, I moved it out of the literal to not block the rest of it from being added

File: build/tradable.js (hunk 1 above)
Comment (TobiTenno) [reply build/tradable.js:2]: sure. i'll do it manually since i'm doing a few changes alongside.

File: config/overrides.json (hunk 2 above)
Comment (TobiTenno) [reply config/overrides.json:153]: sure

File: build/wikia/transformers/transformMod.js (hunk 5 above)
Comment (AyAyEm) [reply build/wikia/transformers/transformMod.js:23]: That could be just an if checking the value instead of letting it give an error it's better by design, at least in my opinion, if you're changing the transform in a pr later we might as well do that there, what do you think? Like a refactor of the transforms?

File: build/tradable.js (hunk 4 above)
Comment (AyAyEm) [reply build/tradable.js:24]: That's what i thought it's not needed to do that but i think it's good practice, so what do you think of reducing the amount of parenthesis? Like:
```suggestion
  const tradableByType = !!(tradableTypes.includes(item.type) && notFiltered)
  const tradableByName = !!(item.uniqueName.match(tradableRegex) || item.name.match(tradableRegex) && notFiltered)
  const tradableByProp = !!(item.isAugment && notFiltered)
```

File: build/wikia/transformers/transformMod.js (hunk 5 above)
Comment (TobiTenno) [reply build/wikia/transformers/transformMod.js:23]: i'm not planning more changes specific to the transforms. I'm planning that warframes will probably have to be updated to support the multi-source pattern that weapons needed.

**Comment by TobiTenno** [comment]
> > 3. I'll take a look at the mods missing images. This wouldn't have removed any, as all of them were removed by the change to stop parsing a good bit of wiki data on master.
> 
> It's not true that this pr did not remove it, as you can see here: [pastebin.com/raw/hiiARwNp](https://pastebin.com/raw/hiiARwNp) (oldItem refers to master branch items) the contrary also happens [pastebin.com/raw/v12QR1vg](https://pastebin.com/raw/v12QR1vg)
> 
> But i don't see not having wikiaThumbnail in certain items as a breaking change so i don't think there'll be a problem to just fix it later.

they aren't on items like Ack & Brunt because the wiki is not giving us image urls for them in our batch fetches. so, like i said, it's not a breaking change that's removed by this, they wouldn't have existed as of the breaking changes that the Wiki made, whose corrective measure (in part, not in whole, because I can't revert or have 100% certainty in their changes) is this PR

File: build/tradable.js (hunk 4 above)
Comment (TobiTenno) [reply build/tradable.js]: added

**Review by AyAyEm — APPROVED** [review]
