### PR TITLE
fix: update inconsistent polarities

### LINKED ISSUE #289: 🚀 Inconsistent casing in polarities key between warframes and weapons
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the upgrade you'd like**
Change the casing to match between weapons and warframes.

**Additional context**
The problem is in the following polarities: **"umbra", "Umbra", "madurai", "Madurai",  "vazarin", "Vazarin", "naramon" and "Naramon".**

Example:
`{ name: 'Atlas', polarities: [ 'naramon', 'vazarin', 'madurai' ] }`
`{ name: 'Agkuza', polarities: [ 'Vazarin' ] }`

_Note: changed my mind about being a bug, please remove the bug label_

### PR DESCRIPTION
**Pull request by TobiTenno**
### What did you fix? (provide a description or issue closes statement)
closes #289 

---

### Reproduction steps
1. Update & unify polarity maps
2. Force polarities to lower case

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter through `npm run lint`? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

### CODE REVIEW

File: build/wikia/transformers/polarities.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+module.exports = {
+  Bar: 'naramon',
+  V: 'madurai',
+  D: 'vazarin',
+  U: 'umbra',
+  Ability: 'zenurik',
+  R: 'unairu'
```
Comment (AyAyEm) [inline build/wikia/transformers/polarities.js:7]: Missing aura polarity.
```suggestion
  R: 'unairu'
  Aura: 'aura'
```

File: build/wikia/transformers/transformWarframe.js [hunk 2]
```diff
@@ -2,23 +2,22 @@
...
-  R: 'unairu'
-}
+const POLARITIES = require('./polarities')
 
 const transformPolarities = ({ Polarities, AuraPolarity }, targetWeapon) => {
   const outputFrame = { ...targetWeapon }
   if (AuraPolarity) {
-    outputFrame.auraPolarity = POLARITIES[AuraPolarity]
+    outputFrame.auraPolarity = (POLARITIES[AuraPolarity] || AuraPolarity || '').toLowerCase()
+    if (outputFrame.auraPolarity && !outputFrame.auraPolarity.length) outputFrame.auraPolarity = undefined
```
Comment (AyAyEm) [inline build/wikia/transformers/transformWarframe.js:11]: Poor design in case there isn't a transformation for a polarity

i think in this case the build should fail, maybe with a more descriptive error than cannot read properties of undefined.
```suggestion
    outputFrame.auraPolarity =POLARITIES[AuraPolarity].toLowerCase()
```

File: build/wikia/transformers/transformWarframe.js [hunk 3]
```diff
@@ -2,23 +2,22 @@
...
+    if (outputFrame.auraPolarity === 'none') outputFrame.auraPolarity = undefined
   }
   if (Polarities) {
-    outputFrame.polarities = Polarities.map(polarity => POLARITIES[polarity])
+    outputFrame.polarities = Polarities.map(polarity => {
+      let out
+      out = (POLARITIES[polarity] || polarity || '').toLowerCase()
+      if (out && !out.length) out = undefined
+      return out
+    }).filter(p => p)
```
Comment (AyAyEm) [inline build/wikia/transformers/transformWarframe.js:20]: Same as above

**Review by AyAyEm — CHANGES_REQUESTED** [review]

File: build/wikia/transformers/transformWarframe.js (hunk 2 above)
Comment (TobiTenno) [reply build/wikia/transformers/transformWarframe.js:11]: No, actually, this is in the case where we don't have a transform because we don't need one. Fallbacks by design aren't lazy if the source data is already correct. Don't need to map something that just needs a text transformation to be right. 

If it needs a mapping anyway, we don't want that to fail the whole build process, because if it's wrong, someone will notice, and the wiki has already stopped using their aliases, so the mapping is just in case they missed an old one.

File: build/wikia/transformers/transformWarframe.js (hunk 3 above)
Comment (TobiTenno) [reply build/wikia/transformers/transformWarframe.js:20]: Same response as above.

File: build/wikia/transformers/transformWarframe.js (hunk 2 above)
Comment (TobiTenno) [reply build/wikia/transformers/transformWarframe.js:11]: The requested change would fail on anything with an undefined mapping, which would fail builds.

**Review by AyAyEm — APPROVED** [review]
